# Scraping Data from a Real Website + Pandas

In [1]:
import time
from bs4 import BeautifulSoup
import undetected_chromedriver as uc

options = uc.ChromeOptions()
driver = uc.Chrome(options=options)

url = "https://www.bps.go.id/id/statistics-table/1/MTAxMCMx/nilai-ekspor-menurut-negara-tujuan-utama--nilai-fob-juta-us----2000-2023.html"
driver.get(url)

time.sleep(10)

html = driver.page_source
driver.quit()

soup = BeautifulSoup(html, "html.parser")
tables = soup.find_all("table")

print(f": {len(tables)}")

: 1

In [10]:
print(soup.find('table').get('class'))

['xl654220']

In [11]:
table = soup.find('table', class_='xl654220')
print(table)

<table border="0" cellpadding="0" cellspacing="0" class="xl654220" style="border-collapse:collapse;width:1461pt;" width="1948">
<colgroup><col width="180"/>
<col span="26" width="68"/>
</colgroup><tbody><tr class="xl824220" style="height:15pt;">
<td class="xl834220" colspan="27" style="height:15pt;width:1461pt;" width="1948">Nilai Ekspor Menurut Negara/Wilayah/Entitas tertentu Tujuan
  Utama (Nilai FOB: juta US$),<span> </span>2000-2025</td>
</tr>
<tr style="height:15pt;">
<td class="xl674220" style="height:15pt;"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
<td class="xl654220"></td>
</tr>
<tr class="xl664220" style="height:35.1pt;">
<td class="xl844220" style="height:35.1pt;width:135pt;" width="180">Negara/Wilayah/Entitas
  tertentu</td>
<td class="xl804220" style="border-left:none;">2000</td>
<td class="xl804220" style="border-left:none;">2001</td>
<td class="xl814220" style="border-left:none;">2002</td>
<td class="xl804220">2003</td>
<td class="xl804220" style="border-left:none;">2004</td>
<td class="xl804220" style="border-left:none;">2005</td>
<td class="xl804220" style="border-left:none;">2006</td>
<td class="xl814220" style="border-left:none;">2007</td>
<td class="xl804220">2008</td>
<td class="xl804220" style="border-left:none;">2009</td>
<td class="xl804220" style="border-left:none;">2010</td>
<td class="xl804220" style="border-left:none;">2011</td>
<td class="xl804220" style="border-left:none;">2012</td>
<td class="xl804220" style="border-left:none;">2013</td>
<td class="xl804220" style="border-left:none;">2014</td>
<td class="xl804220" style="border-left:none;">2015</td>
<td class="xl804220" style="border-left:none;">2016</td>
<td class="xl804220" style="border-left:none;">2017</td>
<td class="xl804220" style="border-left:none;">2018</td>
<td class="xl804220" style="border-left:none;">2019</td>
<td class="xl804220" style="border-left:none;">2020</td>
<td class="xl804220" style="border-left:none;">2021</td>
<td class="xl804220" style="border-left:none;">2022</td>
<td class="xl804220" style="border-left:none;">2023</td>
<td class="xl804220" style="border-left:none;">2024</td>
<td class="xl804220" style="border-left:none;">2025</td>
</tr>
<tr style="height:15pt;">
<td class="xl684220" style="height:15pt;border-top:none;">ASIA</td>
<td class="xl694220" style="border-top:none;border-left:none;"> </td>
<td class="xl704220" style="border-top:none;border-left:none;"> </td>
<td class="xl704220" style="border-top:none;border-left:none;"> </td>
<td class="xl704220" style="border-top:none;border-left:none;"> </td>
<td class="xl704220" style="border-top:none;border-left:none;"> </td>
<td class="xl704220" style="border-top:none;border-left:none;"> </td>
<td class="xl704220" style="border-top:none;border-left:none;"> </td>
<td class="xl704220" style="border-top:none;border-left:none;"> </td>
<td class="xl704220" style="border-top:none;border-left:none;"> </td>
<td class="xl704220" style="border-top:none;border-left:none;"> </td>
<td class="xl704220" style="border-top:none;border-left:none;"> </td>
<td class="xl704220" style="border-top:none;border-left:none;"> </td>
<td class="xl704220" style="border-top:none;border-left:none;"> </td>
<td class="xl704220" style="border-top:none;border-left:none;"> </td>
<td class="xl704220" style="border-top:none;border-left:none;"> </td>
<td class="xl704220" style="border-top:none;border-left:none;"> </td>
<td class="xl704220" style="border-top:none;border-left:none;"> </td>
<td class="xl704220" style="border-top:none;border-left:none;"> </td>
<td class="xl714220" style="border-top:none;border-left:none;"> </td>
<td class="xl704220" style="border-top:none;border-left:none;"> </td>
<td class="xl704220" style="border-top:none;border-left:none;"> </td>
<td class="xl704220" style="border-top:none;border-left:none;"> </td>
<td class="xl704220" style="border-top:none;border-left:none;"> </td>
<td class="xl704220" style="border-top:none;border-left:none;"> </td>
<td class="xl704220" style="border-top:none;border-left:none;"> </td>
<td class="xl704220" style="border-top:none;border-left:none;"> </td>
</tr>
<tr style="height:15pt;">
<td class="xl724220" style="height:15pt;border-top:none;">ASEAN<sup>3)</sup></td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>10.883,7 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>9.507,1 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>9.933,5 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>10.725,4 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>12.997,5 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>15.824,9 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>18.483,1 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>22.292,1 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>27.170,8 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>24.624,0 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>33.347,5 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>42.098,9 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>41.829,1 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>40.630,0 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>39.668,1 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>33.577,0 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>33.778,2 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>39.266,4 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>41.913,2 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>41.464,5 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>36.420,2 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>48.115,2 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>61.354,3 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>53.086,4 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>54.413,7 </td>
<td class="xl734220" style="border-top:none;border-left:none;"><span> </span>58.030,7 </td>
</tr>
<tr style="height:15pt;">
<td class="xl744220" style="height:15pt;border-top:none;">Thailand</td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>1.026,5 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>1.063,6 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>1.227,4 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>1.392,6 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>1.976,2 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>2.246,5 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>2.701,5 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>3.054,3 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>3.661,3 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>3.233,8 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>4.566,6 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>5.896,7 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>6.635,1 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>6.061,9 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>5.783,1 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>5.507,3 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>5.394,0 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>6.473,7 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>6.820,9 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>6.218,4 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>5.110,3 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>7.088,0 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>8.196,8 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>7.222,9 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>7.707,2 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>8.756,8 </td>
</tr>
<tr style="height:15pt;">
<td class="xl744220" style="height:15pt;border-top:none;">Singapura</td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>6.562,4 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>5.363,9 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>5.349,1 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>5.399,7 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>6.001,2 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>7.836,6 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>8.929,8 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>10.501,6 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>12.862,0 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>10.262,7 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>13.723,3 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>18.443,9 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>17.135,0 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>16.686,3 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>16.728,3 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>12.632,6 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>11.861,0 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>12.724,9 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>12.915,0 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>12.916,7 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>10.661,9 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>11.635,8 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>14.349,5 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>12.607,6 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>12.205,1 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>13.438,2 </td>
</tr>
<tr style="height:15pt;">
<td class="xl744220" style="height:15pt;border-top:none;">Filipina</td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>819,5 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>814,8 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>778,2 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>944,7 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>1.237,6 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>1.419,1 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>1.405,7 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>1.853,7 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>2.053,6 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>2.405,9 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>3.180,7 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>3.699,0 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>3.707,6 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>3.817,0 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>3.887,8 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>3.921,7 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>5.270,9 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>6.629,6 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>6.832,2 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>6.770,1 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>5.900,7 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>8.604,3 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>12.905,1 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>11.040,1 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>10.748,4 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>10.220,7 </td>
</tr>
<tr style="height:15pt;">
<td class="xl744220" style="height:15pt;border-top:none;">Malaysia</td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>1.971,8 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>1.778,6 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>2.029,9 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>2.363,9 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>3.016,0 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>3.431,3 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>4.110,8 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>5.096,1 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>6.432,5 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>6.811,8 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>9.362,3 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>10.995,8 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>11.278,3 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>10.666,6 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>9.730,0 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>7.630,9 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>7.069,5 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>8.441,1 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>9.271,6 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>8.801,8 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>8.098,8 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>12.064,7 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>15.672,6 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>12.804,4 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>12.548,8 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>13.061,0 </td>
</tr>
<tr style="height:15pt;">
<td class="xl744220" style="height:15pt;border-top:none;">Myanmar</td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>64,8 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>69,0 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>54,4 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>45,7 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>60,3 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>78,0 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>137,7 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>262,4 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>250,8 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>174,8 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>284,2 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>359,5 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>401,6 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>556,4 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>566,9 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>615,7 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>615,7 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>827,5 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>897,6 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>875,6 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>1.031,9 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>1.122,1 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>964,6 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>796,6 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>620,1 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>787,8 </td>
</tr>
<tr style="height:15pt;">
<td class="xl744220" style="height:15pt;border-top:none;">Kamboja</td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>51,7 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>72,1 </td>
<td class="xl754220" style="border-top:none;border-left:none;"><span> </span>68,8 </td>

In [21]:
header_row = table.find_all('tr')[2]
headers = [' '.join(title.text.split()) for title in header_row.find_all(['td', 'th'])]
print(headers)

['Negara/Wilayah/Entitas tertentu', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']

In [22]:
import pandas as pd

In [23]:
df = pd.DataFrame(columns = headers)
df

Empty DataFrame
Columns: [Negara/Wilayah/Entitas tertentu, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]
Index: []

[0 rows x 27 columns]

In [24]:
from IPython.display import HTML, display

display(
    HTML("""
<style>
.jp-OutputArea-output pre {
    white-space: pre !important;
}
div.output_area pre {
    white-space: pre !important;
}
</style>
""")
)

In [25]:
column_data = table.find_all('tr')

for row in column_data:
    row_data = [
        ' '.join(td.text.split())
        for td in row.find_all('td')
        if td.text.strip() != ''
    ]

    if (
        len(row_data) > 1
        and row_data[0] != 'Negara/Wilayah/Entitas tertentu'
    ):
        print(row_data)

['ASEAN3)', '10.883,7', '9.507,1', '9.933,5', '10.725,4', '12.997,5', '15.824,9', '18.483,1', '22.292,1', '27.170,8', '24.624,0', '33.347,5', '42.098,9', '41.829,1', '40.630,0', '39.668,1', '33.577,0', '33.778,2', '39.266,4', '41.913,2', '41.464,5', '36.420,2', '48.115,2', '61.354,3', '53.086,4', '54.413,7', '58.030,7']
['Thailand', '1.026,5', '1.063,6', '1.227,4', '1.392,6', '1.976,2', '2.246,5', '2.701,5', '3.054,3', '3.661,3', '3.233,8', '4.566,6', '5.896,7', '6.635,1', '6.061,9', '5.783,1', '5.507,3', '5.394,0', '6.473,7', '6.820,9', '6.218,4', '5.110,3', '7.088,0', '8.196,8', '7.222,9', '7.707,2', '8.756,8']
['Singapura', '6.562,4', '5.363,9', '5.349,1', '5.399,7', '6.001,2', '7.836,6', '8.929,8', '10.501,6', '12.862,0', '10.262,7', '13.723,3', '18.443,9', '17.135,0', '16.686,3', '16.728,3', '12.632,6', '11.861,0', '12.724,9', '12.915,0', '12.916,7', '10.661,9', '11.635,8', '14.349,5', '12.607,6', '12.205,1', '13.438,2']
['Filipina', '819,5', '814,8', '778,2', '944,7', '1.237,6', '1.419,1', '1.405,7', '1.853,7', '2.053,6', '2.405,9', '3.180,7', '3.699,0', '3.707,6', '3.817,0', '3.887,8', '3.921,7', '5.270,9', '6.629,6', '6.832,2', '6.770,1', '5.900,7', '8.604,3', '12.905,1', '11.040,1', '10.748,4', '10.220,7']
['Malaysia', '1.971,8', '1.778,6', '2.029,9', '2.363,9', '3.016,0', '3.431,3', '4.110,8', '5.096,1', '6.432,5', '6.811,8', '9.362,3', '10.995,8', '11.278,3', '10.666,6', '9.730,0', '7.630,9', '7.069,5', '8.441,1', '9.271,6', '8.801,8', '8.098,8', '12.064,7', '15.672,6', '12.804,4', '12.548,8', '13.061,0']
['Myanmar', '64,8', '69,0', '54,4', '45,7', '60,3', '78,0', '137,7', '262,4', '250,8', '174,8', '284,2', '359,5', '401,6', '556,4', '566,9', '615,7', '615,7', '827,5', '897,6', '875,6', '1.031,9', '1.122,1', '964,6', '796,6', '620,1', '787,8']
['Kamboja', '51,7', '72,1', '68,8', '79,9', '71,8', '93,9', '103,6', '121,8', '174,0', '201,2', '217,7', '259,5', '292,2', '312,4', '415,8', '429,7', '426,9', '513,9', '525,6', '618,5', '541,3', '531,2', '725,6', '856,1', '833,3', '869,3']
['Brunei Darussalam', '25,5', '21,6', '32,1', '30,4', '31,8', '39,3', '37,6', '43,4', '59,7', '74,9', '61,0', '81,7', '81,8', '122,7', '100,3', '91,2', '88,7', '64,5', '61,2', '103,2', '129,0', '211,4', '240,1', '197,2', '227,8', '187,5']
['Laos', '0,9', '1,4', '0,7', '0,5', '1,6', '1,8', '4,3', '3,7', '4,0', '4,7', '5,5', '8,6', '23,8', '5,8', '4,6', '7,7', '5,9', '4,2', '7,3', '6,8', '5,1', '7,6', '26,6', '16,7', '15,0', '13,3']
['Vietnam', '360,6', '322,1', '392,9', '468,1', '601,0', '678,4', '1.052,0', '1.355,1', '1.672,9', '1.454,2', '1.946,2', '2.354,2', '2.273,7', '2.400,9', '2.451,3', '2.740,2', '3.045,6', '3.586,9', '4.581,9', '5.153,4', '4.941,4', '6.850,1', '8.273,3', '7.544,9', '9.508,0', '10.629,1']
['Timor Leste', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '67,0']
['Jepang', '14.415,2', '13.010,2', '12.045,1', '13.603,5', '15.962,1', '18.049,1', '21.732,1', '23.632,8', '27.743,9', '18.574,7', '25.781,8', '33.714,7', '30.135,1', '27.086,3', '23.117,5', '18.020,9', '16.098,6', '17.798,8', '19.465,6', '16.003,3', '13.664,7', '17.872,7', '24.853,1', '20.787,7', '20.721,1', '17.617,2']
['Hongkong', '1.554,1', '1.290,3', '1.242,3', '1.183,3', '1.387,5', '1.492,3', '1.703,2', '1.687,5', '1.808,8', '2.111,8', '2.501,4', '3.215,5', '2.631,9', '2.693,3', '2.777,6', '2.067,2', '2.144,9', '2.405,8', '2.557,6', '2.501,7', '2.034,9', '2.063,5', '2.960,0', '2.651,5', '2.622,6', '2.289,8']
['Korea Selatan', '-', '-', '4.107,2', '4.323,8', '4.830,2', '7.085,6', '7.693,5', '7.582,7', '9.116,8', '8.145,2', '12.574,6', '16.388,8', '15.049,9', '11.422,5', '10.601,1', '7.664,4', '7.008,9', '8.200,3', '9.540,1', '7.234,4', '6.507,6', '8.981,9', '12.808,8', '10.304,8', '10.773,9', '10.146,0']
['Taiwan', '-', '-', '2.067,5', '2.233,1', '2.854,3', '2.475,0', '2.734,8', '2.596,7', '3.154,7', '3.382,1', '4.837,6', '6.584,9', '6.242,5', '5.862,4', '6.425,1', '5.043,5', '3.655,8', '4.229,2', '4.703,1', '4.034,8', '4.097,4', '6.960,2', '8.678,2', '6.703,9', '6.686,6', '5.543,4']
['Tiongkok1)', '-', '-', '2.902,9', '3.802,5', '4.604,7', '6.662,4', '8.343,6', '9.675,5', '11.636,5', '11.499,3', '15.692,6', '22.941,0', '21.659,5', '22.601,5', '17.605,9', '15.046,4', '16.790,8', '23.083,1', '27.132,2', '27.961,9', '31.781,8', '53.772,5', '65.929,7', '65.036,7', '62.739,6', '66.964,3']
['Lainnya', '13.351,0', '11.862,5', '-', '-', '5.534,2', '7.173,2', '8.566,8', '11.625,6', '15.273,4', '13.498,0', '17.416,6', '22.902,8', '22.059,7', '22.630,6', '24.076,8', '22.128,1', '19.059,6', '24.225,8', '24.133,4', '21.908,3', '20.001,1', '27.588,7', '41.142,6', '36.816,2', '38.328,5', '39.085,6']
['AFRIKA', '1.098,5', '1.181,9', '-', '-', '1.359,4', '1.669,0', '1.985,6', '2.541,9', '3.333,3', '2.802,9', '3.657,0', '5.675,3', '5.713,7', '5.615,5', '6.262,3', '4.759,5', '4.186,3', '4.887,8', '4.782,1', '4.603,4', '4.614,7', '7.065,5', '7.509,5', '6.883,6', '6.343,9', '8.492,9']
['Australia', '1.519,4', '1.844,9', '1.924,4', '1.791,6', '1.887,4', '2.227,6', '2.771,3', '3.394,6', '4.111,0', '3.264,2', '4.244,4', '5.582,5', '4.905,4', '4.370,5', '4.948,4', '3.702,3', '3.208,9', '2.524,4', '2.819,6', '2.328,6', '2.505,7', '3.223,5', '3.466,4', '3.176,8', '4.966,8', '3.733,0']
['Selandia Baru', '-', '-', '-', '-', '187,2', '275,3', '320,0', '362,2', '542,3', '349,5', '396,2', '371,7', '441,0', '469,5', '481,4', '436,2', '366,6', '437,4', '490,7', '447,5', '480,0', '718,8', '731,3', '592,9', '683,0', '780,4']
['Oceania Lainnya', '174,6', '241,1', '246,3', '258,1', '70,1', '85,6', '96,4', '73,6', '167,0', '243,0', '249,8', '348,9', '336,4', '367,5', '308,6', '295,0', '338,1', '302,6', '269,6', '289,8', '304,5', '342,8', '419,1', '517,3', '661,4', '801,8']
['NAFTA', '8.879,3', '8.138,9', '8.200,8', '7.994,0', '9.483,3', '10.609,9', '12.101,2', '12.525,8', '14.108,4', '11.746,5', '15.761,2', '18.077,8', '16.316,7', '17.161,3', '18.136,0', '17.787,1', '17.688,9', '19.602,3', '20.259,0', '19.642,1', '20.348,2', '28.160,9', '31.173,0', '26.733,3', '30.240,1', '35.099,2']
['Amerika Serikat', '8.475,4', '7.748,7', '7.558,6', '7.373,7', '8.767,3', '9.868,5', '11.232,1', '11.614,2', '13.036,9', '10.850,0', '14.266,6', '16.459,1', '14.874,4', '15.691,7', '16.530,1', '16.240,8', '16.141,4', '17.794,5', '18.439,8', '17.844,6', '18.622,5', '25.793,0', '28.197,1', '23.272,2', '26.538,3', '30.947,1']
['Kanada', '403,9', '390,2', '378,0', '382,1', '436,5', '464,3', '551,0', '550,6', '645,4', '512,5', '731,9', '960,3', '792,4', '782,3', '755,0', '722,3', '732,4', '821,2', '913,9', '858,2', '789,1', '1.063,3', '1.276,0', '1.300,2', '1.442,8', '1.697,8']
['Meksiko', '-', '-', '264,2', '238,1', '279,4', '277,1', '318,1', '361,0', '426,1', '384,0', '762,7', '658,4', '649,9', '687,3', '850,9', '824,0', '815,1', '986,6', '905,3', '939,3', '936,5', '1.304,5', '1.699,9', '2.161,0', '2.259,0', '2.454,4']
['Amerika Lainnya', '1.074,6', '993,3', '-', '-', '851,6', '1.053,3', '1.405,0', '1.623,0', '1.972,3', '1.717,2', '2.740,3', '3.295,2', '2.975,2', '3.018,5', '2.899,6', '2.450,2', '2.399,1', '2.576,6', '2.693,4', '2.392,6', '2.296,0', '3.708,8', '4.128,0', '3.802,7', '4.406,1', '5.318,2']
['Uni Eropa2)', '8.855,1', '7.926,0', '8.161,6', '8.230,5', '9.093,2', '10.326,5', '12.029,8', '13.344,5', '15.454,5', '13.568,1', '17.127,4', '20.508,9', '18.027,3', '16.763,7', '16.918,9', '14.842,5', '14.454,8', '16.336,4', '17.087,1', '14.616,7', '13.080,4', '18.002,0', '21.480,9', '16.665,8', '17.416,1', '19.402,0']
['Belanda', '1.837,4', '1.498,2', '1.618,4', '1.401,5', '1.797,5', '2.233,5', '2.518,4', '2.749,4', '3.926,4', '2.909,1', '3.722,5', '5.132,5', '4.664,3', '4.106,0', '3.984,6', '3.442,2', '3.254,9', '4.037,8', '3.896,6', '3.205,0', '3.113,7', '4.630,7', '5.377,8', '3.869,5', '4.749,7', '5.694,8']
['Perancis', '718,3', '662,7', '648,9', '652,8', '659,8', '624,0', '724,4', '802,9', '938,5', '870,2', '1.122,8', '1.284,6', '1.128,2', '1.062,7', '1.019,3', '973,0', '872,7', '975,9', '1.006,8', '1.013,3', '916,3', '1.005,2', '1.081,9', '925,0', '938,7', '1.048,5']
['Jerman', '1.443,1', '1.297,0', '1.269,9', '1.416,8', '1.654,6', '1.781,6', '2.025,7', '2.316,0', '2.465,2', '2.326,7', '2.984,7', '3.304,7', '3.075,0', '2.883,4', '2.821,6', '2.664,2', '2.638,7', '2.668,2', '2.708,2', '2.405,8', '2.456,3', '2.914,8', '3.206,1', '2.523,3', '2.394,1', '2.514,4']
['Belgia', '840,6', '772,1', '782,8', '902,9', '915,6', '997,3', '1.136,3', '1.332,2', '1.351,0', '1.048,3', '1.190,1', '1.374,7', '1.297,7', '1.259,3', '1.217,3', '1.113,3', '1.125,7', '1.241,3', '1.261,2', '1.075,7', '1.220,4', '1.632,0', '2.194,5', '1.634,4', '1.581,2', '1.900,7']
['Denmark', '135,3', '108,8', '102,5', '95,8', '112,2', '127,2', '142,8', '140,8', '170,9', '168,8', '180,2', '250,2', '229,4', '224,5', '226,6', '207,0', '187,6', '192,9', '201,3', '195,3', '163,9', '201,8', '709,3', '147,6', '180,9', '201,0']
['Swedia', '112,8', '118,1', '127,7', '110,4', '115,2', '108,1', '135,4', '109,8', '134,1', '144,3', '156,5', '170,4', '166,3', '162,4', '177,1', '146,8', '144,7', '149,5', '161,2', '155,7', '172,3', '241,1', '253,4', '284,5', '210,5', '184,8']
['Finlandia', '139,9', '116,2', '145,1', '132,1', '148,3', '183,5', '176,6', '121,3', '108,4', '61,2', '122,7', '219,0', '197,8', '149,1', '111,4', '84,9', '83,9', '88,4', '85,1', '76,6', '60,8', '85,4', '92,1', '54,9', '59,3', '54,9']
['Italia', '757,8', '621,8', '719,8', '843,9', '922,6', '1.007,2', '1.213,0', '1.380,0', '1.900,7', '1.651,1', '2.370,0', '3.168,3', '2.277,0', '2.128,6', '2.286,9', '1.872,9', '1.572,1', '1.932,6', '1.920,9', '1.749,3', '1.746,2', '2.805,7', '3.128,0', '2.098,3', '2.251,7', '2.833,0']
['Spanyol', '932,2', '903,6', '996,4', '1.022,4', '837,5', '1.205,5', '1.641,1', '1.906,2', '1.665,3', '1.830,5', '2.328,7', '2.427,9', '2.069,3', '1.810,4', '1.937,6', '1.481,3', '1.579,3', '2.010,1', '2.253,3', '1.599,2', '1.515,7', '2.353,1', '2.287,7', '2.194,4', '2.110,5', '1.806,5']
['Yunani', '98,6', '94,0', '88,5', '95,1', '92,5', '104,8', '125,8', '233,5', '214,3', '165,7', '155,4', '157,5', '139,9', '149,2', '157,4', '143,9', '142,2', '181,3', '230,9', '214,8', '209,6', '228,5', '326,4', '251,2', '249,5', '291,4']
['Polandia', '-', '-', '111,2', '96,2', '101,7', '115,4', '143,5', '190,9', '274,1', '259,7', '313,3', '379,5', '340,0', '365,4', '396,0', '358,9', '370,0', '384,2', '461,2', '483,8', '441,1', '654,6', '1.124,0', '772,1', '726,8', '897,5']
['Uni Eropa Lainnya', '1.839,1', '1.733,5', '1.550,5', '1.460,5', '1.735,9', '1.838,5', '2.046,9', '2.061,5', '2.305,6', '2.132,5', '2.480,5', '2.639,6', '2.442,4', '2.462,7', '2.583,1', '2.354,1', '2.483,0', '2.474,2', '2.900,4', '2.442,2', '1.064,1', '1.248,9', '1.699,7', '1.910,6', '1.963,4', '1.974,5']
['Eropa Lainnya', '318,5', '324,8', '6.327,2', '6.912,5', '482,1', '650,3', '832,1', '1.142,4', '1.426,7', '983,5', '1.450,7', '1.789,7', '1.696,9', '1.858,7', '1.752,7', '2.546,0', '3.954,5', '2.951,3', '2.166,0', '2.253,4', '5.054,4', '5.133,1', '5.551,7', '5.768,3', '5.525,8', '9.200,4']
['Jumlah', '62.124,0', '56.320,9', '57.158,8', '61.058,2', '71.584,6', '85.660,0', '100.798,6', '114.100,9', '137.020,4', '116.510,0', '157.779,1', '203.496,6', '190.020,3', '182.551,8', '175.980,0', '150.366,3', '145.134,0', '168.828,2', '180.012,7', '167.683,0', '163.191,8', '231.710,1', '292.186,7', '259.527,8', '266.529,2', '282.504,9']

In [50]:
import pandas as pd
import re

table = soup.find('table')
rows = table.find_all('tr')

data_parsed = []
benua_sekarang = None
grup_sekarang = None

BENUA_LIST = ['ASIA', 'AFRIKA', 'AUSTRALIA & OCEANIA', 'AMERIKA/AMERICA', 'EROPA']

for row in rows:
    cells = [' '.join(cell.text.split()) for cell in row.find_all(['td', 'th'])]
    cells = [c for c in cells if c != '']
    
    if not cells:
        continue
        
    teks_utama = cells[0]
    teks_bersih = re.sub(r'\d+\)', '', teks_utama).strip()
    
    if any(k in teks_utama for k in ['Nilai Eksport', 'Catatan:', 'Jumlah', 'TOTAL']) or teks_utama.startswith(('1)', '2)', '3)')):
        continue
    if teks_utama in ['Negara/Wilayah/Entitas tertentu', '2000']:
        continue
    if teks_bersih in BENUA_LIST:
        benua_sekarang = teks_bersih
        grup_sekarang = None
        if len(cells) > 1 and teks_bersih == 'AFRIKA':
            data_parsed.append([benua_sekarang, 'AFRIKA', 'AFRIKA'] + cells[1:])

    elif teks_bersih in ['ASEAN', 'NAFTA', 'Uni Eropa']:
        grup_sekarang = teks_bersih
    elif len(cells) > 1:
        if teks_bersih in ['Jepang', 'Hongkong', 'Korea Selatan', 'Taiwan', 'Tiongkok', 'Lainnya'] and benua_sekarang == 'ASIA':
            grup_sekarang = 'Asia Lainnya'

        elif 'Amerika Lainnya' in teks_bersih:
            grup_sekarang = 'Amerika Lainnya'

        elif 'Uni Eropa Lainnya' in teks_bersih:
            grup_sekarang = 'Uni Eropa'

        elif 'Eropa Lainnya' in teks_bersih:
            grup_sekarang = 'Eropa Lainnya'

        data_parsed.append([benua_sekarang, grup_sekarang, teks_bersih] + cells[1:])

header_row = table.find_all('tr')[2]
tahun_headers = [' '.join(th.text.split()) for th in header_row.find_all(['td', 'th']) if '20' in th.text]

kolom = ['Benua', 'Kawasan/Grup', 'Negara'] + tahun_headers
df = pd.DataFrame(data_parsed, columns=kolom)

pd.set_option('display.max_columns', None)
df

,Benua,Kawasan/Grup,Negara,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,ASIA,ASEAN,Thailand,"1.026,5","1.063,6","1.227,4","1.392,6","1.976,2","2.246,5","2.701,5","3.054,3","3.661,3","3.233,8","4.566,6","5.896,7","6.635,1","6.061,9","5.783,1","5.507,3","5.394,0","6.473,7","6.820,9","6.218,4","5.110,3","7.088,0","8.196,8","7.222,9","7.707,2","8.756,8"
1,ASIA,ASEAN,Singapura,"6.562,4","5.363,9","5.349,1","5.399,7","6.001,2","7.836,6","8.929,8","10.501,6","12.862,0","10.262,7","13.723,3","18.443,9","17.135,0","16.686,3","16.728,3","12.632,6","11.861,0","12.724,9","12.915,0","12.916,7","10.661,9","11.635,8","14.349,5","12.607,6","12.205,1","13.438,2"
2,ASIA,ASEAN,Filipina,"819,5","814,8","778,2","944,7","1.237,6","1.419,1","1.405,7","1.853,7","2.053,6","2.405,9","3.180,7","3.699,0","3.707,6","3.817,0","3.887,8","3.921,7","5.270,9","6.629,6","6.832,2","6.770,1","5.900,7","8.604,3","12.905,1","11.040,1","10.748,4","10.220,7"
3,ASIA,ASEAN,Malaysia,"1.971,8","1.778,6","2.029,9","2.363,9","3.016,0","3.431,3","4.110,8","5.096,1","6.432,5","6.811,8","9.362,3","10.995,8","11.278,3","10.666,6","9.730,0","7.630,9","7.069,5","8.441,1","9.271,6","8.801,8","8.098,8","12.064,7","15.672,6","12.804,4","12.548,8","13.061,0"
4,ASIA,ASEAN,Myanmar,"64,8","69,0","54,4","45,7","60,3","78,0","137,7","262,4","250,8","174,8","284,2","359,5","401,6","556,4","566,9","615,7","615,7","827,5","897,6","875,6","1.031,9","1.122,1","964,6","796,6","620,1","787,8"
5,ASIA,ASEAN,Kamboja,"51,7","72,1","68,8","79,9","71,8","93,9","103,6","121,8","174,0","201,2","217,7","259,5","292,2","312,4","415,8","429,7","426,9","513,9","525,6","618,5","541,3","531,2","725,6","856,1","833,3","869,3"
6,ASIA,ASEAN,Brunei Darussalam,"25,5","21,6","32,1","30,4","31,8","39,3","37,6","43,4","59,7","74,9","61,0","81,7","81,8","122,7","100,3","91,2","88,7","64,5","61,2","103,2","129,0","211,4","240,1","197,2","227,8","187,5"
7,ASIA,ASEAN,Laos,"0,9","1,4","0,7","0,5","1,6","1,8","4,3","3,7","4,0","4,7","5,5","8,6","23,8","5,8","4,6","7,7","5,9","4,2","7,3","6,8","5,1","7,6","26,6","16,7","15,0","13,3"
8,ASIA,ASEAN,Vietnam,"360,6","322,1","392,9","468,1","601,0","678,4","1.052,0","1.355,1","1.672,9","1.454,2","1.946,2","2.354,2","2.273,7","2.400,9","2.451,3","2.740,2","3.045,6","3.586,9","4.581,9","5.153,4","4.941,4","6.850,1","8.273,3","7.544,9","9.508,0","10.629,1"
9,ASIA,ASEAN,Timor Leste,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,"67,0"
10,ASIA,Asia Lainnya,Jepang,"14.415,2","13.010,2","12.045,1","13.603,5","15.962,1","18.049,1","21.732,1","23.632,8","27.743,9","18.574,7","25.781,8","33.714,7","30.135,1","27.086,3","23.117,5","18.020,9","16.098,6","17.798,8","19.465,6","16.003,3","13.664,7","17.872,7","24.853,1","20.787,7","20.721,1","17.617,2"
11,ASIA,Asia Lainnya,Hongkong,"1.554,1","1.290,3","1.242,3","1.183,3","1.387,5","1.492,3","1.703,2","1.687,5","1.808,8","2.111,8","2.501,4","3.215,5","2.631,9","2.693,3","2.777,6","2.067,2","2.144,9","2.405,8","2.557,6","2.501,7","2.034,9","2.063,5","2.960,0","2.651,5","2.622,6","2.289,8"
12,ASIA,Asia Lainnya,Korea Selatan,-,-,"4.107,2","4.323,8","4.830,2","7.085,6","7.693,5","7.582,7","9.116,8","8.145,2","12.574,6","16.388,8","15.049,9","11.422,5","10.601,1","7.664,4","7.008,9","8.200,3","9.540,1","7.234,4","6.507,6","8.981,9","12.808,8","10.304,8","10.773,9","10.146,0"
13,ASIA,Asia Lainnya,Taiwan,-,-,"2.067,5","2.233,1","2.854,3","2.475,0","2.734,8","2.596,7","3.154,7","3.382,1","4.837,6","6.584,9","6.242,5","5.862,4","6.425,1","5.043,5","3.655,8","4.229,2","4.703,1","4.034,8","4.097,4","6.960,2","8.678,2","6.703,9","6.686,6","5.543,4"
14,ASIA,Asia Lainnya,Tiongkok,-,-,"2.902,9","3.802,5","4.604,7","6.662,4","8.343,6","9.675,5","11.636,5","11.499,3","15.692,6","22.941,0","21.659,5","22.601,5","17.605,9","15.046,4","16.790,8","23.083,1","27.132,2","27.961,9","31.781,8","53.772,5","65.929,7","65.036,7","62.739,6","66.964,3"
15,ASIA,Asia Lainnya,Lainnya,"13.351,0","11.862,5",-,-,"5.534,2","7.173,2","8.566,8","11.625,6","15.273,4","13.498,0","17.416,6","22.902,8","22.059,7","22.630,6","24.076,8","22.128,1","19.059,6","24.225,8","24.133,4","21.908,3","20.001,1","27.588,7","41.142,6","36.816,2","38.328,5","39.085,6"
16,AFRIKA,AFRIKA,AFRIKA,"1.098,5","1.181,9",-,-,"1.359,4","1.669,0","1.985,6","2.541,9","3.333,3","2.802,9","3.657,0","5.675,3","5.713,7","5.615,5","6.262,3","4.759,5","4.186,3","4.887,8","4.782,1","4.603,4","4.614,7","7.065,5","7.509,5","6.883,6","6.343,9","8.492,9"
17,AUSTRALIA & OCEANIA,NaN,Australia,"1.519,4","1.844,9","1.924,4","1.791,6","1.887,4","2.227,6","2.771,3","3.394,6","4.111,0","3.264,2","4.244,4","5.582,5","4.905,4","4.370,5","4.948,4","3.702,3","3.208,9","2.524,4","2.819,6","2.328,6","2.505,7","3.223,5","3.466,4","3.176,8","4.966,8","3.733,0"
18,AUSTRALIA & OCEANIA,NaN,Selandia Baru,-,-,-,-,"187,2","275,3","320,0","362,2","542,3","349,5","396,2","371,7","441,0","469,5","481,4","436,2","366,6","437,4","490,7","447,5","480,0","718,8","731,3","592,9","683,0","780,4"
19,AUSTRALIA & OCEANIA,NaN,Oceania Lainnya,"174,6","241,1","246,3","258,1","70,1","85,6","96,4","73,6","167,0","243,0","249,8","348,9","336,4","367,5","308,6","295,0","338,1","302,6","269,6","289,8","304,5","342,8","419,1","517,3","661,4","801,8"
20,AMERIKA/AMERICA,NAFTA,Amerika Serikat,"8.475,4","7.748,7","7.558,6","7.373,7","8.767,3","9.868,5","11.232,1","11.614,2","13.036,9","10.850,0","14.266,6","16.459,1","14.874,4","15.691,7","16.530,1","16.240,8","16.141,4","17.794,5","18.439,8","17.844,6","18.622,5","25.793,0","28.197,1","23.272,2","26.538,3","30.947,1"
21,AMERIKA/AMERICA,NAFTA,Kanada,"403,9","390,2","378,0","382,1","436,5","464,3","551,0","550,6","645,4","512,5","731,9","960,3","792,4","782,3","755,0","722,3","732,4","821,2","913,9","858,2","789,1","1.063,3","1.276,0","1.300,2","1.442,8","1.697,8"
22,AMERIKA/AMERICA,NAFTA,Meksiko,-,-,"264,2","238,1","279,4","277,1","318,1","361,0","426,1","384,0","762,7","658,4","649,9","687,3","850,9","824,0","815,1","986,6","905,3","939,3","936,5","1.304,5","1.699,9","2.161,0","2.259,0","2.454,4"
23,AMERIKA/AMERICA,Amerika Lainnya,Amerika Lainnya,"1.074,6","993,3",-,-,"851,6","1.053,3","1.405,0","1.623,0","1.972,3","1.717,2","2.740,3","3.295,2","2.975,2","3.018,5","2.899,6","2.450,2","2.399,1","2.576,6","2.693,4","2.392,6","2.296,0","3.708,8","4.128,0","3.802,7","4.406,1","5.318,2"
24,EROPA,Uni Eropa,Belanda,"1.837,4","1.498,2","1.618,4","1.401,5","1.797,5","2.233,5","2.518,4","2.749,4","3.926,4","2.909,1","3.722,5","5.132,5","4.664,3","4.106,0","3.984,6","3.442,2","3.254,9","4.037,8","3.896,6","3.205,0","3.113,7","4.630,7","5.377,8","3.869,5","4.749,7","5.694,8"
25,EROPA,Uni Eropa,Perancis,"718,3","662,7","648,9","652,8","659,8","624,0","724,4","802,9","938,5","870,2","1.122,8","1.284,6","1.128,2","1.062,7","1.019,3","973,0","872,7","975,9","1.006,8","1.013,3","916,3","1.005,2","1.081,9","925,0","938,7","1.048,5"
26,EROPA,Uni Eropa,Jerman,"1.443,1","1.297,0","1.269,9","1.416,8","1.654,6","1.781,6","2.025,7","2.316,0","2.465,2","2.326,7","2.984,7","3.304,7","3.075,0","2.883,4","2.821,6","2.664,2","2.638,7","2.668,2","2.708,2","2.405,8","2.456,3","2.914,8","3.206,1","2.523,3","2.394,1","2.514,4"
27,EROPA,Uni Eropa,Belgia,"840,6","772,1","782,8","902,9","915,6","997,3","1.136,3","1.332,2","1.351,0","1.048,3","1.190,1","1.374,7","1.297,7","1.259,3","1.217,3","1.113,3","1.125,7","1.241,3","1.261,2","1.075,7","1.220,4","1.632,0","2.194,5","1.634,4","1.581,2","1.900,7"
28,EROPA,Uni Eropa,Denmark,"135,3","108,8","102,5","95,8","112,2","127,2","142,8","140,8","170,9","168,8","180,2","250,2","229,4","224,5","226,6","207,0","187,6","192,9","201,3","195,3","163,9","201,8","709,3","147,6","180,9","201,0"
29,EROPA,Uni Eropa,Swedia,"112,8","118,1","127,7","110,4","115,2","108,1","135,4","109,8","134,1","144,3","156,5","170,4","166,3","162,4","177,1","146,8","144,7","149,5","161,2","155,7","172,3","241,1","253,4","284,5","210,5","184,8"
30,EROPA,Uni Eropa,Finlandia,"139,9","116,2","145,1","132,1","148,3","183,5","176,6","121,3","108,4","61,2","122,7","219,0","197,8","149,1","111,4","84,9","83,9","88,4","85,1","76,6","60,8","85,4","92,1","54,9","59,3","54,9"
31,EROPA,Uni Eropa,Italia,"757,8","621,8","719,8","843,9","922,6","1.007,2","1.213,0","1.380,0","1.900,7","1.651,1","2.370,0","3.168,3","2.277,0","2.128,6","2.286,9","1.872,9","1.572,1","1.932,6","1.920,9","1.749,3","1.746,2","2.805,7","3.128,0","2.098,3","2.251,7","2.833,0"
32,EROPA,Uni Eropa,Spanyol,"932,2","903,6","996,4","1.022,4","837,5","1.205,5","1.641,1","1.906,2","1.665,3","1.830,5","2.328,7","2.427,9","2.069,3","1.810,4","1.937,6","1.481,3","1.579,3","2.010,1","2.253,3","1.599,2","1.515,7","2.353,1","2.287,7","2.194,4","2.110,5","1.806,5"
33,EROPA,Uni Eropa,Yunani,"98,6","94,0","88,5","95,1","92,5","104,8","125,8","233,5","214,3","165,7","155,4","157,5","139,9","149,2","157,4","143,9","142,2","181,3","230,9","214,8","209,6","228,5","326,4","251,2","249,5","291,4"
34,EROPA,Uni Eropa,Polandia,-,-,"111,2","96,2","101,7","115,4","143,5","190,9","274,1","259,7","313,3","379,5","340,0","365,4","396,0","358,9","370,0","384,2","461,2","483,8","441,1","654,6","1.124,0","772,1","726,8","897,5"
35,EROPA,Uni Eropa,Uni Eropa Lainnya,"1.839,1","1.733,5","1.550,5","1.460,5","1.735,9","1.838,5","2.046,9","2.061,5","2.305,6","2.132,5","2.480,5","2.639,6","2.442,4","2.462,7","2.583,1","2.354,1","2.483,0","2.474,2","2.900,4","2.442,2","1.064,1","1.248,9","1.699,7","1.910,6","1.963,4","1.974,5"
36,EROPA,Eropa Lainnya,Eropa Lainnya,"318,5","324,8","6.327,2","6.912,5","482,1","650,3","832,1","1.142,4","1.426,7","983,5","1.450,7","1.789,7","1.696,9","1.858,7","1.752,7","2.546,0","3.954,5","2.951,3","2.166,0","2.253,4","5.054,4","5.133,1","5.551,7","5.768,3","5.525,8","9.200,4"

In [51]:
df.to_csv(
    r'E:\Python project\web scraping with jupyter notebook\data_expor_BPS.csv',
    index=False)